# render.yaml
services:
  - type: web
    name: traffic-prediction-api
    runtime: python
    repo: https://github.com/hassene22/traffic_prediction_api.git
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0